### ISSUE TITLE
Định nghĩa NUI và một vài ví dụ về NUI

### ISSUE THREAD

**Issue by daohoang18398** [thanhnguyenduy2304/NUI#1]
[Định nghĩa NUI.pdf](https://github.com/thanhnguyenduy2304/NUI/files/983792/D.nh.nghia.NUI.pdf)

**Comment by NguyenTinh98** [comment]
[LỊCH SỬ HÌNH THÀNH VÀ PHÁT TRIỂN CỦA NATURAL USER  INTERACE.docx](https://github.com/thanhnguyenduy2304/NUI/files/984148/L.CH.S.HINH.THANH.VA.PHAT.TRI.N.C.A.NATURAL.USER.INTERACE.docx)
